/**
 * ResearchPilot AI - Export Utilities
 * Allows exporting research reports, roadmaps, reviews, and notes
 * to Markdown files or triggering beautiful, print-ready PDF windows.
 */

export const ExportService = {
  /**
   * Export content as a Markdown (.md) file download
   */
  exportToMarkdown(filename, title, content) {
    const markdownContent = `# ${title}\n\n*Generated by ResearchPilot AI*\n\n${content}`;
    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${filename.toLowerCase().replace(/[^a-z0-9]+/g, "_")}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },

  /**
   * Open a printable window and print a beautiful PDF layout
   */
  exportToPDF(title, htmlContent) {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      alert("Please allow popups to export PDFs.");
      return;
    }

    printWindow.document.write(`
      <html>
        <head>
          <title>${title} - ResearchPilot AI</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@600;700&display=swap');
            body {
              font-family: 'Inter', sans-serif;
              color: #0f172a;
              line-height: 1.6;
              padding: 2.5rem;
              max-width: 800px;
              margin: 0 auto;
            }
            h1, h2, h3, h4 {
              font-family: 'Outfit', sans-serif;
              color: #1e1b4b;
              margin-top: 1.5rem;
              margin-bottom: 0.75rem;
            }
            h1 {
              font-size: 2.25rem;
              border-bottom: 2px solid #e2e8f0;
              padding-bottom: 0.75rem;
              color: #7c3aed;
            }
            h2 {
              font-size: 1.5rem;
              color: #0f172a;
            }
            ul, ol {
              margin-bottom: 1rem;
              padding-left: 1.5rem;
            }
            li {
              margin-bottom: 0.5rem;
            }
            .meta-header {
              font-size: 0.85rem;
              color: #64748b;
              margin-bottom: 2rem;
              display: flex;
              justify-content: space-between;
              border-bottom: 1px solid #e2e8f0;
              padding-bottom: 0.5rem;
            }
            .watermark {
              text-align: center;
              font-size: 0.75rem;
              color: #94a3b8;
              margin-top: 4rem;
              border-top: 1px solid #e2e8f0;
              padding-top: 1rem;
            }
            code {
              font-family: monospace;
              background: #f1f5f9;
              padding: 0.2rem 0.4rem;
              border-radius: 4px;
              font-size: 0.9em;
            }
            blockquote {
              border-left: 4px solid #7c3aed;
              padding-left: 1rem;
              margin-left: 0;
              color: #475569;
              font-style: italic;
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="meta-header">
            <span>Generated by ResearchPilot AI</span>
            <span>Date: ${new Date().toLocaleDateString()}</span>
          </div>
          <div class="content-body">
            ${htmlContent}
          </div>
          <div class="watermark">
            ResearchPilot AI • Accelerating Scientific & Academic Discovery
          </div>
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }
};
